{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "99b8e3c1-3ea4-4591-aab5-b91a005b7910",
   "metadata": {},
   "outputs": [],
   "source": [
    "from PIL import Image\n",
    "from io import BytesIO"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "7c2bbac7-bdd8-4d6f-a6c4-fe5cdae445d0",
   "metadata": {},
   "outputs": [],
   "source": [
    "#  Pillow\n",
    "try:\n",
    "    from PIL import Image\n",
    "    HAS_PILLOW = True\n",
    "except ImportError:\n",
    "    print(\"⚠️ 警告: 没有安装 Pillow 库 (pip install Pillow)。图片将不会被压缩，文件体积可能很大。\")\n",
    "    HAS_PILLOW = False\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "4d368e77-dbf0-4add-abdc-f737158c933c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import folium\n",
    "from folium.features import DivIcon\n",
    "import base64\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "627462b9-27f9-40a5-a8c6-de858f29ac0e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define the set of locations that will have a 360° tour link and special icon effect.\n",
    "TOUR_LOCATIONS = {\n",
    "    \"顾炎武纪念馆\", \"顾炎武石像\",\"亭林园顾炎武纪念馆\", \"昆曲博物馆\", \"昆石馆\", \"爱莲亭\",\n",
    "    \"录竹居\", \"养馀园\", \"戒石碑\", \"革命烈士陵园\"\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "904ad092-1bfa-48a4-914b-d0766cbfb284",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ================= 1. 配置区域 =================\n",
    "\n",
    "# 图片文件夹路径\n",
    "IMAGE_FOLDER = \"pictures\"\n",
    "\n",
    "# 地点数据列表 (双语 + 详细描述 + 视频链接)\n",
    "locations = [\n",
    "    {\n",
    "        \"name_cn\": \"亭林园顾炎武纪念馆\", \n",
    "        \"name_en\": \"Gu Yanwu Memorial Hall\",\n",
    "        \"lat\": 31.393724, \"lon\": 120.947496,\n",
    "        \"type_cn\": \"博物馆\", \"type_en\": \"Museum\",\n",
    "        \"desc_cn\": \"纪念明末清初著名思想家顾炎武先生的专题纪念馆。馆内陈列其生平事迹、著作及学术成就，弘扬'天下兴亡，匹夫有责'的爱国主义精神。\",\n",
    "        \"desc_en\": \"A memorial hall dedicated to Gu Yanwu, a famous scholar of the late Ming and early Qing dynasties. It displays his life story and academic achievements, highlighting his famous quote: 'Everyone is responsible for the rise and fall of the world'.\",\n",
    "        \"img\": \"guyanwu_museum.jpg\",\n",
    "        \"memory_index\": 0 \n",
    "    },\n",
    "    {\n",
    "        \"name_cn\": \"昆曲博物馆\", \n",
    "        \"name_en\": \"Kunqu Opera Museum\",\n",
    "        \"lat\": 31.392813, \"lon\":120.947891,\n",
    "        \"type_cn\": \"文化\", \"type_en\": \"Culture\",\n",
    "        \"desc_cn\": \"展示'百戏之祖'昆曲艺术的殿堂。通过戏台、服饰、乐器等展品，全方位呈现昆曲的历史源流与艺术魅力。\",\n",
    "        \"desc_en\": \"A museum showcasing the art of Kunqu Opera, known as the 'Ancestor of All Dramas'. It presents the history and charm of Kunqu through stages, costumes, and instruments.\",\n",
    "        \"img\": \"kunqu.jpg\",\n",
    "        \"memory_index\": 1\n",
    "    },\n",
    "    {\n",
    "        \"name_cn\": \"机器人饮品站\", \n",
    "        \"name_en\": \"Robot Drink Station\",\n",
    "        \"lat\": 31.392641, \"lon\": 120.947228,\n",
    "        \"type_cn\": \"服务\", \"type_en\": \"Service\",\n",
    "        \"desc_cn\": \"亭林园内的现代科技体验点，机械臂现场制作饮品，将传统园林与现代科技完美融合。\",\n",
    "        \"desc_en\": \"A modern tech experience spot in Tinglin Garden, where robotic arms prepare drinks on-site, blending traditional gardens with modern technology.\",\n",
    "        \"img\": \"robot_drink.jpg\",\n",
    "        \"video_link\": \"detail_robot.html\"\n",
    "    },\n",
    "    {\n",
    "        \"name_cn\": \"祖冲之像\", \n",
    "        \"name_en\": \"Statue of Zu Chongzhi\",\n",
    "        \"lat\": 31.392113, \"lon\": 120.946239,\n",
    "        \"type_cn\": \"雕像\", \"type_en\": \"Statue\",\n",
    "        \"desc_cn\": \"纪念曾在昆山任县令的古代伟大数学家、天文学家祖冲之。他将圆周率精确到小数点后七位。\",\n",
    "        \"desc_en\": \"A statue commemorating Zu Chongzhi, the great ancient mathematician and astronomer who served as a magistrate in Kunshan. He calculated Pi to seven decimal places.\",\n",
    "        \"img\": \"zuchongzhi.jpg\"\n",
    "    },\n",
    "\n",
    "      {\n",
    "        \"name_cn\": \"昆石馆\",\n",
    "        \"name_en\": \"Kun Stone Gallery\",\n",
    "        \"lat\": 31.394680, \"lon\": 120.948121,\n",
    "        \"type_cn\": \"展馆\",\n",
    "        \"type_en\": \"Gallery\",\n",
    "        \"desc_cn\": \"展示昆石与园林石文化的空间。\",\n",
    "        \"desc_en\": \"A gallery dedicated to Kun stones and traditional garden rock culture.\",\n",
    "        \"img\": \"kunstone.jpg\",\n",
    "        \"memory_index\": 2\n",
    "       \n",
    "    },\n",
    "\n",
    "    {\n",
    "        \"name_cn\": \"留晖亭\", \"name_en\": \"Liuhui Pavilion\",\n",
    "        \"lat\": 31.389771, \"lon\": 120.941559,\n",
    "        \"type_cn\": \"亭台\", \"type_en\": \"Pavilion\",\n",
    "        \"desc_cn\": \"亭依山而建，位置绝佳，可在此欣赏朝晖夕阴之美，是休憩观景的好去处。\",\n",
    "        \"desc_en\": \"Built against the mountain, this pavilion offers a perfect spot to enjoy the beauty of sunrise and sunset.\",\n",
    "        \"img\": \"liuhui.jpg\"\n",
    "    },\n",
    "    {\n",
    "        \"name_cn\": \"问石苑\", \"name_en\": \"Wenshi Garden\",\n",
    "        \"lat\": 31.390062, \"lon\": 120.941870,\n",
    "        \"type_cn\": \"园林\", \"type_en\": \"Garden\",\n",
    "        \"desc_cn\": \"园中奇石林立，汇集了众多形态各异的昆石，展现了昆山深厚的石文化底蕴。\",\n",
    "        \"desc_en\": \"Filled with unique rock formations, this garden showcases the profound stone culture of Kunshan through various Kunstones.\",\n",
    "        \"img\": \"wenshi.jpg\"\n",
    "    },\n",
    "    {\n",
    "        \"name_cn\": \"琼华阁\", \"name_en\": \"Qionghua Pavilion\",\n",
    "        \"lat\": 31.391128, \"lon\": 120.940179,\n",
    "        \"type_cn\": \"建筑\", \"type_en\": \"Building\",\n",
    "        \"desc_cn\": \"因琼花而得名，建筑古朴典雅。每当春日来临，琼花盛开，洁白如玉，蔚为壮观。\",\n",
    "        \"desc_en\": \"Named after the Jade Flower (Viburnum), this elegant building is surrounded by spectacular white blooms in spring.\",\n",
    "        \"img\": \"qionghua.jpg\"\n",
    "    },\n",
    "    {\n",
    "        \"name_cn\": \"并蒂莲池\", \"name_en\": \"Twin Lotus Pond\",\n",
    "        \"lat\": 31.394367, \"lon\": 120.948376,\n",
    "        \"type_cn\": \"水景\", \"type_en\": \"Pond\",\n",
    "        \"desc_cn\": \"池中种植着珍稀的并蒂莲，象征着吉祥喜庆，是夏日赏荷的绝佳地点。\",\n",
    "        \"desc_en\": \"Home to the rare Twin Lotus, symbolizing good fortune and happiness. An excellent spot for viewing lotuses in summer.\",\n",
    "        \"img\": \"lotus_pond.jpg\"\n",
    "    },\n",
    "    {\n",
    "        \"name_cn\": \"玉峰门\", \"name_en\": \"Yufeng Gate\",\n",
    "        \"lat\": 31.393350, \"lon\": 120.947234,\n",
    "        \"type_cn\": \"大门\", \"type_en\": \"Gate\",\n",
    "        \"desc_cn\": \"亭林园的主要入口之一，气势恢宏，上方匾额题字苍劲有力。\",\n",
    "        \"desc_en\": \"One of the main entrances to Tinglin Garden, featuring magnificent architecture and powerful calligraphy on the plaque.\",\n",
    "        \"img\": \"yufeng_gate.jpg\"\n",
    "    },\n",
    "    {\n",
    "        \"name_cn\": \"千年银杏\", \"name_en\": \"Millennium Ginkgo\",\n",
    "        \"lat\": 31.393331, \"lon\": 120.947115,\n",
    "        \"type_cn\": \"古树\", \"type_en\": \"Ancient Tree\",\n",
    "        \"desc_cn\": \"这株银杏树历经千年风雨，依然枝繁叶茂。深秋时节，金叶满地，美不胜收。\",\n",
    "        \"desc_en\": \"Verify weathering a thousand years, this ginkgo tree remains lush. In late autumn, its golden leaves create a breathtaking scene.\",\n",
    "        \"img\": \"ginkgo.jpg\"\n",
    "    },\n",
    "    \n",
    "    \n",
    "    {\"name_cn\": \"岁寒亭\", \"name_en\": \"Suihan Pavilion\", \n",
    "     \"lat\": 31.390355, \"lon\": 120.941198,\n",
    "     \"type_cn\": \"亭台\", \"type_en\": \"Pavilion\", \n",
    "     \"desc_cn\": \"取意‘岁寒，然后知松柏之后凋也’。\", \n",
    "     \"desc_en\": \"Symbolizing resilience in winter.\", \n",
    "     \"img\": \"suihan.jpg\"},\n",
    "    \n",
    "    {\"name_cn\": \"揽山亭\", \"name_en\": \"Lanshan Pavilion\", \n",
    "     \"lat\": 31.390958 , \"lon\": 120.941150,\n",
    "     \"type_cn\": \"亭台\", \"type_en\": \"Pavilion\", \n",
    "     \"desc_cn\": \"登高望远。\", \"desc_en\": \"High vantage point.\", \n",
    "     \"img\": \"lanshan.jpg\"},\n",
    "    \n",
    "    {\"name_cn\": \"香雪\", \"name_en\": \"Xiangxue\", \n",
    "     \"lat\": 31.391848, \"lon\": 120.940073,\n",
    "     \"type_cn\": \"景观\", \"type_en\": \"Scenic\", \n",
    "     \"desc_cn\": \"梅花盛开如雪。\", \"desc_en\": \"Plum blossoms like snow.\", \n",
    "     \"img\": \"xiangxue.jpg\"},\n",
    "    \n",
    "    {\"name_cn\": \"水云居\", \"name_en\": \"Shuiyunju\", \n",
    "     \"lat\": 31.392246, \"lon\": 120.940403, \n",
    "     \"type_cn\": \"茶室\", \"type_en\": \"Teahouse\", \n",
    "     \"desc_cn\": \"临水而居。\", \"desc_en\": \"Living by the water.\", \n",
    "     \"img\": \"shuiyunju.jpg\"},\n",
    "    \n",
    "    {\"name_cn\": \"猫空\", \"name_en\": \"Momomi Cafe\", \n",
    "     \"lat\": 31.391582, \"lon\": 120.940302,\n",
    "     \"type_cn\": \"咖啡\", \"type_en\": \"Cafe\", \n",
    "     \"desc_cn\": \"书店与咖啡。\", \"desc_en\": \"Bookstore and cafe.\", \n",
    "     \"img\": \"maokong.jpg\"},\n",
    "\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"娄曲堂\",\n",
    "    \"name_en\": \"Louqu Hall\",\n",
    "    \"lat\": 31.392028, \"lon\": 120.940924,\n",
    "    \"type_cn\": \"戏台\",\n",
    "    \"type_en\": \"Stage\",\n",
    "    \"desc_cn\": \"亭林园中类似戏台的亭子空间，曾用于传统表演与集会活动。\",\n",
    "    \"desc_en\": \"A pavilion resembling a traditional opera stage, historically used for performances and gatherings.\",\n",
    "    \"img\": \"louqu.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"含晖亭\",\n",
    "    \"name_en\": \"Han Hui Pavilion\",\n",
    "    \"lat\": 31.391863, \"lon\": 120.940962,\n",
    "    \"type_cn\": \"亭台\",\n",
    "    \"type_en\": \"Pavilion\",\n",
    "    \"desc_cn\": \"取“含光纳晖”之意的观景亭，适合驻足休憩。\",\n",
    "    \"desc_en\": \"A pavilion named for embracing light and glow, ideal for resting and viewing the surroundings.\",\n",
    "    \"img\": \"hanhui.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"山高水长\",\n",
    "    \"name_en\": \"Mountains High, Waters Long Bridge\",\n",
    "    \"lat\": 31.391168, \"lon\": 120.942022,\n",
    "    \"type_cn\": \"桥\",\n",
    "    \"type_en\": \"Bridge\",\n",
    "    \"desc_cn\": \"连接亭林园主园与留晖园的重要桥梁，寓意精神绵延不绝。\",\n",
    "    \"desc_en\": \"A bridge linking the main Tinglin Garden and Liuhui Garden, symbolizing enduring spirit and continuity.\",\n",
    "    \"img\": \"shangaoshuichang.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"好吃集市\",\n",
    "    \"name_en\": \"Yummy Market\",\n",
    "    \"lat\":31.391557, \"lon\": 120.941787,\n",
    "    \"type_cn\": \"市集\",\n",
    "    \"type_en\": \"Market\",\n",
    "    \"desc_cn\": \"园内市集，提供烤串、煎饼、棉花糖等小吃，充满生活气息。\",\n",
    "    \"desc_en\": \"A lively garden market offering skewers, pancakes, cotton candy, and other snacks.\",\n",
    "    \"img\": \"haochi.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"夕秀轩\",\n",
    "    \"name_en\": \"Xixiu Pavilion\",\n",
    "    \"lat\": 31.392739, \"lon\": 120.941594,\n",
    "    \"type_cn\": \"亭台\",\n",
    "    \"type_en\": \"Pavilion\",\n",
    "    \"desc_cn\": \"在傍晚光影中尤为秀美的建筑空间。\",\n",
    "    \"desc_en\": \"A pavilion especially beautiful in the soft evening light.\",\n",
    "    \"img\": \"xixiu.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"荷香榭\",\n",
    "    \"name_en\": \"Lotus Fragrance Pavilion\",\n",
    "    \"lat\": 31.392392, \"lon\": 120.941540,\n",
    "    \"type_cn\": \"水榭\",\n",
    "    \"type_en\": \"Waterside Pavilion\",\n",
    "    \"desc_cn\": \"临水而建，夏季荷花盛开时清香四溢。\",\n",
    "    \"desc_en\": \"A waterside pavilion filled with lotus fragrance in summer.\",\n",
    "    \"img\": \"hexiang.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"玉犀双亭\",\n",
    "    \"name_en\": \"Twin Jade Rhinoceros Pavilions\",\n",
    "    \"lat\": 31.394017, \"lon\": 120.947993,\n",
    "    \"type_cn\": \"亭台\",\n",
    "    \"type_en\": \"Pavilion\",\n",
    "    \"desc_cn\": \"成对而立的亭子，因石刻与造型得名。\",\n",
    "    \"desc_en\": \"A pair of pavilions named after jade-like stone features.\",\n",
    "    \"img\": \"yuxi.jpg\"\n",
    "  },\n",
    "\n",
    "\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"琼花王\",\n",
    "    \"name_en\": \"King of Qionghua\",\n",
    "    \"lat\": 31.393330, \"lon\": 120.948924,\n",
    "    \"type_cn\": \"古树\",\n",
    "    \"type_en\": \"Ancient Tree\",\n",
    "    \"desc_cn\": \"亭林园著名古树，被誉为“琼花王”。\",\n",
    "    \"desc_en\": \"A famous ancient tree known as the King of Qionghua.\",\n",
    "    \"img\": \"qionghua_king.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"戒石碑\",\n",
    "    \"name_en\": \"Admonition Stone Stele\",\n",
    "    \"lat\": 31.393075, \"lon\": 120.948308,\n",
    "    \"type_cn\": \"碑刻\",\n",
    "    \"type_en\": \"Stele\",\n",
    "    \"desc_cn\": \"象征清廉与自省精神的石碑。\",\n",
    "    \"desc_en\": \"A stone stele symbolizing integrity and self-discipline.\",\n",
    "    \"img\": \"jieshi.jpg\",\n",
    "    \"memory_index\": 6\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"顾炎武石像\",\n",
    "    \"name_en\": \"Gu Yanwu Statue\",\n",
    "    \"lat\": 31.393474, \"lon\": 120.948087,\n",
    "    \"type_cn\": \"雕塑\",\n",
    "    \"type_en\": \"Statue\",\n",
    "    \"desc_cn\": \"思想家顾炎武的石像，园内精神核心之一。\",\n",
    "    \"desc_en\": \"A stone statue of Gu Yanwu, representing the spiritual core of the garden.\",\n",
    "    \"img\": \"guyanwu_statue.jpg\",\n",
    "    \"memory_index\": 0 \n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"录竹居\",\n",
    "    \"name_en\": \"Luzhu Courtyard\",\n",
    "    \"lat\": 31.392127,  \"lon\":120.946970,\n",
    "    \"type_cn\": \"庭院\",\n",
    "    \"type_en\": \"Courtyard\",\n",
    "    \"desc_cn\": \"以竹为主题的静谧庭院空间。\",\n",
    "    \"desc_en\": \"A tranquil courtyard themed around bamboo.\",\n",
    "    \"img\": \"luzhu_courtyard.jpg\",\n",
    "    \"memory_index\": 4\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"春风亭\",\n",
    "    \"name_en\": \"Spring Breeze Pavilion\",\n",
    "    \"lat\": 31.392257, \"lon\": 120.946672,\n",
    "    \"type_cn\": \"亭台\",\n",
    "    \"type_en\": \"Pavilion\",\n",
    "    \"desc_cn\": \"春季尤为宜人的观景亭。\",\n",
    "    \"desc_en\": \"A pavilion best enjoyed during springtime breezes.\",\n",
    "    \"img\": \"chunfeng.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"丹实琼芳\",\n",
    "    \"name_en\": \"Red Fruit & Jade Fragrance\",\n",
    "    \"lat\": 31.391831, \"lon\": 120.945908,\n",
    "    \"type_cn\": \"景点\",\n",
    "    \"type_en\": \"Scenic Spot\",\n",
    "    \"desc_cn\": \"由树木与奇石构成的园林景观组合。\",\n",
    "    \"desc_en\": \"A scenic composition of trees and ornamental rocks.\",\n",
    "    \"img\": \"danshiqiongfang.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"养馀园\",\n",
    "    \"name_en\": \"Yangyu Garden\",\n",
    "    \"lat\": 31.391675, \"lon\": 120.945031,\n",
    "    \"type_cn\": \"庭院 / 咖啡店\",\n",
    "    \"type_en\": \"Courtyard / Café\",\n",
    "    \"desc_cn\": \"拾级而上进入的庭院空间，内设咖啡店与盆栽陈设。\",\n",
    "    \"desc_en\": \"A courtyard reached by steps, featuring a café and potted plants.\",\n",
    "    \"img\": \"yangyu_garden.jpg\",\n",
    "    \"memory_index\": 5\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"牡丹亭\",\n",
    "    \"name_en\": \"Peony Pavilion\",\n",
    "    \"lat\": 31.392805,  \"lon\": 120.946696,\n",
    "    \"type_cn\": \"亭台\",\n",
    "    \"type_en\": \"Pavilion\",\n",
    "    \"desc_cn\": \"临水而建的传统园林亭阁，以《牡丹亭》意象命名，体现江南园林中诗意与戏曲文化的融合。\",\n",
    "    \"desc_en\": \"A waterside pavilion inspired by the classical drama The Peony Pavilion, embodying the poetic and theatrical spirit of Jiangnan garden aesthetics.\",\n",
    "    \"img\": \"mudan.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"花雨轩\",\n",
    "    \"name_en\": \"Flower Rain Pavilion\",\n",
    "    \"lat\": 31.391309, \"lon\": 120.944622,\n",
    "    \"type_cn\": \"亭台\",\n",
    "    \"type_en\": \"Pavilion\",\n",
    "    \"desc_cn\": \"花木繁盛时如雨般飘落的观赏空间。\",\n",
    "    \"desc_en\": \"A pavilion where falling petals resemble gentle rain.\",\n",
    "    \"img\": \"huayu.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"小西湖\",\n",
    "    \"name_en\": \"Small West Lake\",\n",
    "    \"lat\":31.390602,  \"lon\":120.943483,\n",
    "    \"type_cn\": \"湖泊\",\n",
    "    \"type_en\": \"Lake\",\n",
    "    \"desc_cn\": \"‘小西湖’，园中特色水域景观之一，水面开阔宁静。\",\n",
    "    \"desc_en\": \"A calm and open water feature within the garden. It's also called small 'West Lake'.\",\n",
    "    \"img\": \"chuncai_lake.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"爱莲亭\",\n",
    "    \"name_en\": \"Lotus Appreciation Pavilion\",\n",
    "    \"lat\": 31.391593, \"lon\": 120.942543,\n",
    "    \"type_cn\": \"亭台\",\n",
    "    \"type_en\": \"Pavilion\",\n",
    "    \"desc_cn\": \"体现“爱莲”品格的观景亭。\",\n",
    "    \"desc_en\": \"A pavilion celebrating the virtue and beauty of lotus flowers.\",\n",
    "    \"img\": \"ailian.jpg\",\n",
    "    \"memory_index\": 3\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"罗汉桥\",\n",
    "    \"name_en\": \"Arhat Bridge\",\n",
    "    \"lat\": 31.391351, \"lon\": 120.942443,\n",
    "    \"type_cn\": \"桥\",\n",
    "    \"type_en\": \"Bridge\",\n",
    "    \"desc_cn\": \"园内造型古朴的桥梁景观。\",\n",
    "    \"desc_en\": \"A traditional-style bridge within the garden.\",\n",
    "    \"img\": \"luohan_bridge.jpg\"\n",
    "  },\n",
    "\n",
    "  {\n",
    "    \"name_cn\": \"影山轩\",\n",
    "    \"name_en\": \"Shadow Mountain Pavilion\",\n",
    "    \"lat\": 31.391419, \"lon\": 120.940895,\n",
    "    \"type_cn\": \"亭台\",\n",
    "    \"type_en\": \"Pavilion\",\n",
    "    \"desc_cn\": \"以走廊与光影变化见长的空间。\",\n",
    "    \"desc_en\": \"A space known for its galleria forest and shifting light and shadow.\",\n",
    "    \"img\": \"yingshan.jpg\"\n",
    "  },\n",
    "\n",
    "    {\n",
    "      \"name_cn\": \"革命烈士陵园\",\n",
    "      \"name_en\": \"Revolutionary Martyrs’ Cemetery\",\n",
    "      \"lat\": 31.395059, \n",
    "      \"lon\": 120.948594,\n",
    "      \"type_cn\": \"纪念地\",\n",
    "      \"type_en\": \"Memorial Site\",\n",
    "      \"desc_cn\": \"纪念近现代革命烈士的纪念空间，环境庄重肃穆，是昆山重要的爱国主义教育与历史记忆场所。\",\n",
    "      \"desc_en\": \"A solemn memorial dedicated to revolutionary martyrs, serving as an important site of patriotic education and collective historical memory in Kunshan.\",\n",
    "      \"img\": \"geming.jpg\",\n",
    "      \"memory_index\": 8\n",
    "    },\n",
    "    {\n",
    "      \"name_cn\": \"文笔峰\",\n",
    "      \"name_en\": \"Wenbi Peak\",\n",
    "      \"lat\": 31.392501,\n",
    "      \"lon\": 120.943750,\n",
    "      \"type_cn\": \"观景点\",\n",
    "      \"type_en\": \"Scenic Viewpoint\",\n",
    "      \"desc_cn\": \"玉峰山东峰，因山势挺拔如文笔得名。清代康熙帝曾登临题“鸢飞鱼跃”，为亭林园重要的人文地标。\",\n",
    "      \"desc_en\": \"The eastern peak of Yufeng Mountain, named for its brush-like silhouette. Emperor Kangxi once visited and inscribed “Kites Soaring, Fish Leaping,” marking it as a key cultural landmark.\",\n",
    "      \"img\": \"wenbi.jpg\"\n",
    "    },\n",
    "    {\n",
    "      \"name_cn\": \"玉峰山（马鞍山）\",\n",
    "      \"name_en\": \"Yufeng Mountain (Ma’an Hill)\",\n",
    "      \"lat\": 31.393130, \n",
    "      \"lon\": 120.944585,\n",
    "      \"type_cn\": \"自然景观\",\n",
    "      \"type_en\": \"Natural Landmark\",\n",
    "      \"desc_cn\": \"昆山境内唯一山体，海拔80.8米，因石色洁白如玉得名。山体由寒武纪硅质灰岩构成，形成玲珑石地貌。自南朝建慧聚寺，至清代康熙登临题字，园内汇集顾炎武纪念馆与昆石文化遗存，是自然与人文交织的核心象征。\",\n",
    "      \"desc_en\": \"The only natural hill in Kunshan, rising 80.8 meters above the plain. Named for its jade-like white limestone, the mountain features distinctive Cambrian quartz-rich rock formations. With origins tracing back to the Liang Dynasty’s Huiju Temple and later imperial visits, it integrates natural geology with layered cultural heritage, including Gu Yanwu memorial sites and Kun stone history.\",\n",
    "      \"img\": \"yufeng_mountain.jpg\"\n",
    "    },\n",
    "    {\n",
    "      \"name_cn\": \"玉出昆冈\",\n",
    "      \"name_en\": \"Jade from the Kun Ridge Archway\",\n",
    "      \"lat\": 31.392214, \n",
    "      \"lon\": 120.949087,\n",
    "      \"type_cn\": \"牌坊 / 文化象征\",\n",
    "      \"type_en\": \"Archway / Cultural Symbol\",\n",
    "      \"desc_cn\": \"亭林园东大门牌坊题“玉出昆冈”。“玉”既指玉峰山所产洁白玲珑的昆石（石英含量高达98%以上，被誉为“石中之玉”），亦喻昆山人杰地灵、贤才辈出。对联中“归奇顾怪”分别指归庄与顾炎武，象征此地物华天宝与人文鼎盛。\",\n",
    "      \"desc_en\": \"The eastern entrance archway bears the inscription “Jade from the Kun Ridge.” The word “jade” refers both to the locally quarried Kun stone-renowned for its translucent, jade-like beauty—and metaphorically to the talented figures born in Kunshan. The couplet references Gui Zhuang and Gu Yanwu, celebrating both material richness and intellectual heritage.\",\n",
    "      \"img\": \"yuchukungang.jpg\"\n",
    "    },\n",
    "    {\n",
    "      \"name_cn\": \"亭林园西入口\",\n",
    "      \"name_en\": \"Tinglin Garden West Entrance\",\n",
    "      \"lat\": 31.389261,\n",
    "      \"lon\": 120.941908,\n",
    "      \"type_cn\": \"园林入口\",\n",
    "      \"type_en\": \"Garden Entrance\",\n",
    "      \"desc_cn\": \"西入口悬挂“亭林园”匾额，由此进入留晖园景区。空间由城市过渡至园林，形成视觉与情绪的缓冲，是游览动线的重要起点。\",\n",
    "      \"desc_en\": \"Marked by the plaque “Tinglin Garden,” the west entrance leads visitors into the Liuhui Garden section. It serves as a spatial threshold, transitioning from urban context into classical garden scenery and shaping the visitor’s experiential sequence.\",\n",
    "      \"img\": \"west_entrance.jpg\"\n",
    "    },\n",
    "    {\n",
    "      \"name_cn\": \"妙峰塔\",\n",
    "      \"name_en\": \"Miaofeng Pagoda\",\n",
    "      \"lat\": 31.393190, \n",
    "      \"lon\":120.945942,\n",
    "      \"type_cn\": \"古塔\",\n",
    "      \"type_en\": \"Ancient Pagoda\",\n",
    "      \"desc_cn\": \"仿木塔结构建造，设有腰檐与栏杆。塔身各层雕刻佛像，兼具宗教象征与精细石刻艺术，是玉峰山重要的历史遗存。\",\n",
    "      \"desc_en\": \"A stone pagoda modeled after traditional wooden tower structures, complete with projecting eaves and railings. Each level features carved Buddha figures, combining religious symbolism with refined stone craftsmanship.\",\n",
    "      \"img\": \"miaofeng.jpg\"\n",
    "    },\n",
    "\n",
    "    {\n",
    "      \"name_cn\": \"一览亭\",\n",
    "      \"name_en\": \"Yilan Pavilion\",\n",
    "      \"lat\": 31.393190, \n",
    "      \"lon\": 120.945369,\n",
    "      \"type_cn\": \"观景亭\",\n",
    "      \"type_en\": \"Scenic Pavilion\",\n",
    "      \"desc_cn\": \"位于玉峰山接近山顶，可俯瞰昆山城景。登亭远望，现代建筑与自然山水交织成景，展现城市发展与传统山林空间的对话。\",\n",
    "      \"desc_en\": \"Located above midway up Yufeng Mountain, this pavilion offers panoramic views of Kunshan. From here, visitors observe the layered skyline where modern urban forms merge with natural hills and waterways.\",\n",
    "      \"img\": \"yilan.jpg\"\n",
    "    }\n",
    "\n",
    "\n",
    "]\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "3f5b61a4-da8d-44dc-941b-657f6cac46c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "from PIL import Image\n",
    "from io import BytesIO\n",
    "from PIL import ExifTags  #  ExifTags\n",
    "\n",
    "def get_base64_image(image_filename):\n",
    "    if not image_filename:\n",
    "        return \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=\" \n",
    "    \n",
    "    path = os.path.join(IMAGE_FOLDER, image_filename)\n",
    "    \n",
    "    # file\n",
    "    if not os.path.exists(path):\n",
    "        if os.path.exists(IMAGE_FOLDER):\n",
    "            folder_files = os.listdir(IMAGE_FOLDER)\n",
    "            base = os.path.basename(path)\n",
    "            for f in folder_files:\n",
    "                if f.lower() == base.lower():\n",
    "                    path = os.path.join(IMAGE_FOLDER, f)\n",
    "                    break\n",
    "    \n",
    "    if not os.path.exists(path):\n",
    "        print(f\"警告: 找不到图片 {image_filename}\")\n",
    "        return \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=\" \n",
    "\n",
    "    try:\n",
    "        with Image.open(path) as img:\n",
    "            # === 新增：处理手机照片旋转 (Exif Orientation) ===\n",
    "            try:\n",
    "                for orientation in ExifTags.TAGS.keys():\n",
    "                    if ExifTags.TAGS[orientation] == 'Orientation':\n",
    "                        break\n",
    "                exif = img._getexif()\n",
    "                if exif is not None:\n",
    "                    orientation = exif.get(orientation)\n",
    "                    if orientation == 3:\n",
    "                        img = img.rotate(180, expand=True)\n",
    "                    elif orientation == 6:\n",
    "                        img = img.rotate(270, expand=True)\n",
    "                    elif orientation == 8:\n",
    "                        img = img.rotate(90, expand=True)\n",
    "            except (AttributeError, KeyError, IndexError):\n",
    "                pass\n",
    "                \n",
    "            # RGB\n",
    "            if img.mode in (\"RGBA\", \"P\"):\n",
    "                img = img.convert(\"RGB\")\n",
    "            \n",
    "            # 压缩逻辑：如果宽度大于 400px，就等比缩小\n",
    "            if img.width > 400:\n",
    "                ratio = 400 / img.width\n",
    "                new_height = int(img.height * ratio)\n",
    "                img = img.resize((400, new_height), Image.Resampling.LANCZOS)\n",
    "            \n",
    "            # 保存到内存缓冲区\n",
    "            buffered = BytesIO()\n",
    "            # 降低质量保存为 JPEG，quality=70 足够清晰且体积很小\n",
    "            img.save(buffered, format=\"JPEG\", quality=70)\n",
    "            \n",
    "            return f\"data:image/jpeg;base64,{base64.b64encode(buffered.getvalue()).decode('utf-8')}\"\n",
    "            \n",
    "    except Exception as e:\n",
    "        print(f\"处理图片错误 {image_filename}: {e}\")\n",
    "        return \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=\" \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "edcb7b60-5739-4756-beca-5c9034851f80",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<folium.raster_layers.TileLayer at 0x16315ce80>"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# ================= 3. Map =================\n",
    "\n",
    "CENTER_LAT = 31.392806\n",
    "CENTER_LON = 120.944707\n",
    "\n",
    "m = folium.Map(\n",
    "    location=[CENTER_LAT, CENTER_LON],\n",
    "    zoom_start=16, \n",
    "    tiles=None,   \n",
    "    control_scale=True\n",
    ")\n",
    "\n",
    "# OpenStreetMap \n",
    "folium.TileLayer(\n",
    "    tiles=\"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png\",\n",
    "    attr='&copy; <a href=\"https://www.openstreetmap.org/#map=17/31.392284/120.943862\" target=\"_blank\">OpenStreetMap contributors</a>',\n",
    "    name=\"OpenStreetMap\"\n",
    ").add_to(m)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "8e484f68-b7f2-4185-aa32-2c174cb69859",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "正在处理 43 个地点...\n",
      "成功！地图已生成并保存至: tinglin_map_with_tours.html\n"
     ]
    }
   ],
   "source": [
    "print(f\"正在处理 {len(locations)} 个地点...\")\n",
    "\n",
    "for loc in locations:\n",
    "    # data\n",
    "    name_cn = loc.get(\"name_cn\", \"未知地点\")\n",
    "    name_en = loc.get(\"name_en\", \"Unknown Spot\")\n",
    "    desc_cn = loc.get(\"desc_cn\", \"暂无描述\").replace(\"'\", \"&#39;\")\n",
    "    desc_en = loc.get(\"desc_en\", \"No description available.\").replace(\"'\", \"&#39;\")\n",
    "    type_cn = loc.get(\"type_cn\", \"景点\")\n",
    "    type_en = loc.get(\"type_en\", \"Spot\")\n",
    "    \n",
    "    # img\n",
    "    img_name = loc.get(\"img\", \"\")\n",
    "    img_src = get_base64_image(img_name)\n",
    "    \n",
    "    # 3. video\n",
    "    # --- \"View Detail\" Button (Original Logic) ---\n",
    "    video_btn_html = \"\"\n",
    "    if \"video_link\" in loc and loc[\"video_link\"]:\n",
    "        target_url = loc[\"video_link\"]\n",
    "        btn_text = \"查看详情 / View Detail\"\n",
    "        video_btn_html = f\"\"\"\n",
    "        <div style=\"margin-top: 15px;\">\n",
    "            <a href=\"{target_url}\" target=\"_blank\" style=\"display: flex; ...\">\n",
    "                <span style=\"margin-right: 8px;\">👉</span> {btn_text}\n",
    "            </a>\n",
    "        </div>\n",
    "        \"\"\"\n",
    "\n",
    "    # --- NEW: \"360° Tour\" Button ---\n",
    "    # It now checks for 'memory_index' and creates a postMessage button.\n",
    "    tour_btn_html = \"\"\n",
    "    is_tour_location = \"memory_index\" in loc\n",
    "\n",
    "    if is_tour_location:\n",
    "        memory_index = loc[\"memory_index\"]\n",
    "        tour_btn_text = \"进入360全景游览 / Enter 360° Tour\"\n",
    "        \n",
    "        # This 'onclick' JavaScript sends the message to your app.html page\n",
    "        onclick_js = f\"window.parent.postMessage({{ type: 'openMemory', index: {memory_index} }}, '*'); return false;\"\n",
    "\n",
    "        tour_btn_html = f\"\"\"\n",
    "        <div style=\"margin-top: 15px;\">\n",
    "            <a href=\"#\" onclick=\"{onclick_js}\" style=\"display: flex; align-items: center; justify-content: center; width: 100%; padding: 10px 0; background: linear-gradient(135deg, #FFD700, #FFA500); color: white; text-decoration: none; border-radius: 8px; font-size: 14px; font-weight: bold; box-shadow: 0 4px 6px rgba(255, 165, 0, 0.4); transition: transform 0.2s;\" onmouseover=\"this.style.transform='scale(1.02)'\" onmouseout=\"this.style.transform='scale(1)'\">\n",
    "                <span style=\"margin-right: 8px;\">🌐</span> {tour_btn_text}\n",
    "            </a>\n",
    "        </div>\n",
    "        \"\"\"\n",
    "\n",
    "    html_content = f\"\"\"\n",
    "    <div style=\"font-family: 'Noto Sans SC', 'Helvetica Neue', Arial, sans-serif; width: 320px; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.2);\">\n",
    "        <div style=\"position: relative; height: 200px; overflow: hidden; background: #f0f0f0; display: flex; align-items: center; justify-content: center;\">\n",
    "            <div style=\"position: absolute; top: -10%; left: -10%; width: 120%; height: 120%; background-image: url('{img_src}'); background-size: cover; background-position: center; filter: blur(10px) brightness(0.8); z-index: 0;\"></div>\n",
    "            <img src=\"{img_src}\" style=\"position: relative; z-index: 1; max-width: 100%; max-height: 100%; object-fit: contain; box-shadow: 0 5px 15px rgba(0,0,0,0.3);\" />\n",
    "            <div style=\"position: absolute; top: 12px; right: 12px; background: rgba(255,255,255,0.95); padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: bold; color: #2E8B57; box-shadow: 0 2px 4px rgba(0,0,0,0.15); z-index: 2;\">\n",
    "                {type_cn} {type_en}\n",
    "            </div>\n",
    "        </div>\n",
    "        <div style=\"padding: 20px;\">\n",
    "            <div style=\"margin-bottom: 12px; border-bottom: 1px solid #eee; padding-bottom: 10px;\">\n",
    "                <h3 style=\"margin: 0; font-size: 20px; color: #333; font-weight: 800;\">{name_cn}</h3>\n",
    "                <p style=\"margin: 4px 0 0; font-size: 13px; color: #888; font-style: italic;\">{name_en}</p>\n",
    "            </div>\n",
    "            <div style=\"max-height: 150px; overflow-y: auto;\">\n",
    "                <p style=\"font-size: 13px; line-height: 1.6; color: #444; margin-bottom: 8px;\">{desc_cn}</p>\n",
    "                <p style=\"font-size: 12px; line-height: 1.5; color: #777; font-style: italic;\">{desc_en}</p>\n",
    "            </div>\n",
    "            {video_btn_html}\n",
    "            {tour_btn_html}\n",
    "        </div>\n",
    "    </div>\n",
    "    \"\"\"\n",
    "    popup = folium.Popup(html_content, max_width=360)\n",
    "\n",
    "    # --- MODIFICATION: 带特效的图标 ---\n",
    "    icon_animation_style = \"\"\n",
    "    icon_final_style = f\"\"\"\n",
    "        width: 36px; height: 36px; border-radius: 50%;\n",
    "        border: 2px solid #ffffff; box-shadow: 0 4px 8px rgba(0,0,0,0.4);\n",
    "        background-image: url('{img_src}'); background-position: center center;\n",
    "        background-size: cover; position: relative;\n",
    "    \"\"\"\n",
    "    \n",
    "    if is_tour_location:\n",
    "        # Define a pulsing gold animation and apply it to the icon's style\n",
    "        icon_animation_style = \"\"\"\n",
    "        <style>\n",
    "            @keyframes pulse-gold {\n",
    "                0% { box-shadow: 0 0 0 0px rgba(255, 215, 0, 0.9), 0 4px 8px rgba(0,0,0,0.4); }\n",
    "                70% { box-shadow: 0 0 0 10px rgba(255, 215, 0, 0), 0 4px 8px rgba(0,0,0,0.4); }\n",
    "                100% { box-shadow: 0 0 0 0px rgba(255, 215, 0, 0), 0 4px 8px rgba(0,0,0,0.4); }\n",
    "            }\n",
    "        </style>\n",
    "        \"\"\"\n",
    "        icon_final_style += \" animation: pulse-gold 2s infinite;\"\n",
    "\n",
    "    icon_html = f\"\"\"\n",
    "        {icon_animation_style}\n",
    "        <div style=\"{icon_final_style}\"></div>\n",
    "        <div style=\"position: absolute; bottom: -6px; left: 50%; transform: translateX(-50%); width: 0; height: 0; border-left: 6px solid transparent; border-right: 6px solid transparent; border-top: 6px solid #ffffff;\"></div>\n",
    "    \"\"\"\n",
    "    \n",
    "    # --- Add Marker (same as before) ---\n",
    "    folium.Marker(\n",
    "        location=[loc[\"lat\"], loc[\"lon\"]],\n",
    "        popup=popup,\n",
    "        tooltip=f\"{name_cn} {name_en}\",\n",
    "        icon=DivIcon(icon_size=(40, 50), icon_anchor=(20, 50), html=icon_html)\n",
    "    ).add_to(m)\n",
    "\n",
    "# ================= 4. Map =================\n",
    "output_file = \"tinglin_map_with_tours.html\"\n",
    "m.save(output_file)\n",
    "\n",
    "print(f\"成功！地图已生成并保存至: {output_file}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a2d78aef-6076-4e02-8201-aa9d310f5e3b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
